name: loginwithdiscuz
main: cn.sevaft.plugins.minecraft.loginwithdiscuz.main.Loginwithdiscuz
version: 0.1alpha
author: stevennight
description: A auth plugin with discuz bbs.
commands:
  login:
    description: This is a login command.
    usage: |
      /<command> [password]
  setloginlocal:
    description: This is a set login position command.Player must a OP.
    usage: |
      /<command> (default)
  logout:
    description: This is a logout command.
    usage: |
      /<command>
  lwd:
    description: This is a lwd help command.
    usage: |
      /<command> [type]